/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skyapp;

import cek_validasi.EmptyValidation;
import database.User;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Kelompok 1 (TI 2020 C)
 */
public class Login extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    int counter;
    
    
    public Login() {
        this.setIconImage(new ImageIcon("src//images//logo//Logo.png").getImage());
        initComponents();
        this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_forgot = new javax.swing.JLabel();
        lbl_close = new javax.swing.JLabel();
        lbl_minimize = new javax.swing.JLabel();
        lbl_signin = new javax.swing.JLabel();
        lbl_pindah_signup = new javax.swing.JLabel();
        txt_username_login = new javax.swing.JTextField();
        txt_password_login = new javax.swing.JPasswordField();
        panel_gambarLogin = new javax.swing.JPanel();
        lbl_gambar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SkyApp Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 800));
        getContentPane().setLayout(null);

        lbl_forgot.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lbl_forgot.setForeground(new java.awt.Color(0, 0, 0));
        lbl_forgot.setText("Forgot your password?");
        lbl_forgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_forgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_forgotMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_forgotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_forgotMouseExited(evt);
            }
        });
        getContentPane().add(lbl_forgot);
        lbl_forgot.setBounds(150, 490, 170, 30);

        lbl_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_close);
        lbl_close.setBounds(450, 10, 40, 40);

        lbl_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_minimize);
        lbl_minimize.setBounds(400, 10, 40, 40);

        lbl_signin.setBackground(new java.awt.Color(0, 167, 255));
        lbl_signin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_signinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_signinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_signinMouseExited(evt);
            }
        });
        getContentPane().add(lbl_signin);
        lbl_signin.setBounds(100, 620, 110, 90);

        lbl_pindah_signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_pindah_signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_pindah_signupMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_pindah_signup);
        lbl_pindah_signup.setBounds(300, 620, 120, 90);

        txt_username_login.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        txt_username_login.setForeground(new java.awt.Color(54, 64, 77));
        txt_username_login.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_username_login.setText("username");
        txt_username_login.setBorder(null);
        txt_username_login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_username_loginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_username_loginFocusLost(evt);
            }
        });
        getContentPane().add(txt_username_login);
        txt_username_login.setBounds(150, 390, 230, 25);

        txt_password_login.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        txt_password_login.setForeground(new java.awt.Color(54, 64, 77));
        txt_password_login.setText("Password");
        txt_password_login.setBorder(null);
        txt_password_login.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_password_login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_password_loginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_password_loginFocusLost(evt);
            }
        });
        getContentPane().add(txt_password_login);
        txt_password_login.setBounds(150, 450, 230, 24);

        panel_gambarLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_gambarLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_gambarLoginMouseDragged(evt);
            }
        });
        panel_gambarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_gambarLoginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panel_gambarLoginMouseReleased(evt);
            }
        });
        panel_gambarLogin.setLayout(null);

        lbl_gambar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page/Login.png"))); // NOI18N
        lbl_gambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel_gambarLogin.add(lbl_gambar);
        lbl_gambar.setBounds(0, 0, 500, 800);

        getContentPane().add(panel_gambarLogin);
        panel_gambarLogin.setBounds(0, 0, 500, 800);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void isEnter (JLabel btn) {
        btn.setBackground(new Color(9, 50, 236));
    }
    
    void isExit (JLabel btn) {
        btn.setBackground(new Color(0, 0, 255));
    }
    
    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_closeMouseClicked

    private void lbl_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizeMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_lbl_minimizeMouseClicked

    private void panel_gambarLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_gambarLoginMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panel_gambarLoginMousePressed

    private void panel_gambarLoginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_gambarLoginMouseDragged
       panel_gambarLogin.setCursor(Cursor.getPredefinedCursor(Cursor.MOVE_CURSOR));
       
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();

       this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panel_gambarLoginMouseDragged

    private void txt_username_loginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_username_loginFocusGained
        if(txt_username_login.getText().equals("username")){
            txt_username_login.setText("");
        }

        txt_username_login.setForeground(new Color (54, 64, 77));
    }//GEN-LAST:event_txt_username_loginFocusGained

    private void txt_username_loginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_username_loginFocusLost
        if(txt_username_login.getText().equals("")){
            txt_username_login.setText("username");
        }

        txt_username_login.setForeground(new Color(54, 64, 77));                                 
    }//GEN-LAST:event_txt_username_loginFocusLost

    private void txt_password_loginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_password_loginFocusGained
        if(new String (txt_password_login.getPassword()).equals("Password")){
            txt_password_login.setText("");
        }

        txt_password_login.setForeground(new Color(54, 64, 77));
    }//GEN-LAST:event_txt_password_loginFocusGained

    private void txt_password_loginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_password_loginFocusLost
        if(new String (txt_password_login.getPassword()).equals("")){
            txt_password_login.setText("Password");
        }

        txt_password_login.setForeground(new Color(54,64, 77));
    }//GEN-LAST:event_txt_password_loginFocusLost

    private void lbl_signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_signinMouseClicked
        String cek = EmptyValidation.cekLogin(txt_username_login,txt_password_login);

        if(cek.equals("valid")) {
            String username = txt_username_login.getText();
            String password = new String(txt_password_login.getPassword());
            
            boolean isSuccess = new User().verifikasi_user(username, password);
            
            if (isSuccess) {
                JOptionPane.showMessageDialog(null,"LOGIN BERHASIL", "BERHASIL", JOptionPane.INFORMATION_MESSAGE);
                Loading ld = new Loading(username);
                ld.setVisible(true);       
                dispose();
            } else {
                this.counter += 1;
                JOptionPane.showMessageDialog(null,"LOGIN GAGAL " + this.counter + "X", "GAGAL", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(null,"USERNAME ATAU PASSWORD SALAH", "GAGAL", JOptionPane.INFORMATION_MESSAGE);
            }
            
            if(counter == 3) {
                JOptionPane.showMessageDialog(null,"DIKELUARKAN DARI SISTEM", "KELUAR", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
            
        } else {
            JOptionPane.showMessageDialog(null, cek);
        }  
    }//GEN-LAST:event_lbl_signinMouseClicked

    private void lbl_pindah_signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pindah_signupMouseClicked
        Register rg = new Register();

        rg.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_pindah_signupMouseClicked

    private void lbl_signinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_signinMouseEntered
        isEnter(lbl_signin);
    }//GEN-LAST:event_lbl_signinMouseEntered

    private void lbl_signinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_signinMouseExited
        isExit(lbl_signin);
    }//GEN-LAST:event_lbl_signinMouseExited

    private void panel_gambarLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_gambarLoginMouseReleased
        panel_gambarLogin.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_panel_gambarLoginMouseReleased

    private void lbl_forgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_forgotMouseClicked
        Reset rst = new Reset();
        
        rst.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_forgotMouseClicked

    private void lbl_forgotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_forgotMouseEntered
        lbl_forgot.setForeground(new Color(0, 167,  255));
    }//GEN-LAST:event_lbl_forgotMouseEntered

    private void lbl_forgotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_forgotMouseExited
        lbl_forgot.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_lbl_forgotMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_forgot;
    private javax.swing.JLabel lbl_gambar;
    private javax.swing.JLabel lbl_minimize;
    private javax.swing.JLabel lbl_pindah_signup;
    private javax.swing.JLabel lbl_signin;
    private javax.swing.JPanel panel_gambarLogin;
    private javax.swing.JPasswordField txt_password_login;
    private javax.swing.JTextField txt_username_login;
    // End of variables declaration//GEN-END:variables
}
