/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skyapp;

import database.Transaksi;
import list_aplikasi.SPT;
import list_aplikasi.VID;
import list_aplikasi.PST;
import list_aplikasi.TEN;
import list_aplikasi.VIU;
import list_aplikasi.GOP;
import list_games.ML;
import list_games.CODM;
import list_games.LOL;
import list_games.FF;
import list_games.GI;
import list_games.Valorant;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import list_aplikasi.STEAM;
import list_games.AOV;
import list_games.HONKAI;
import list_games.LM;
import list_games.PB;
import list_games.RAGNA;



/**
 *
 * @author Kelompok 1 (TI 2020 C)
 */
public class Menu extends javax.swing.JFrame {
    
    int xMouse;
    int yMouse;
    
    public String user;
    
    Object currentWindow = this;
    
    public Menu(String user) {
        this.setIconImage(new ImageIcon("src//images//logo//Logo.png").getImage());
        initComponents();   
        
        lbl_user.setText(user);
        Transaksi.set_rupiah(user, lbl_rupiah);
        this.user = user;
        
        panel_aplikasi.setBackground(new Color(255, 255, 255));
        panel_games.setBackground(new Color(255, 255, 255));
        list_aplikasi.setBackground(new Color(255, 255, 255));
        list_games.setBackground(new Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_utama = new javax.swing.JPanel();
        lbl_skyapp = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        lbl_rupiah = new javax.swing.JLabel();
        lbl_saldo = new javax.swing.JLabel();
        icon_coin = new javax.swing.JLabel();
        lbl_selamatdatang = new javax.swing.JLabel();
        separator_saldo = new javax.swing.JSeparator();
        separator_atas = new javax.swing.JSeparator();
        panel_games = new javax.swing.JScrollPane();
        list_games = new javax.swing.JPanel();
        lbl_genshin = new javax.swing.JLabel();
        lbl_ml = new javax.swing.JLabel();
        lbl_ff = new javax.swing.JLabel();
        lbl_valorant = new javax.swing.JLabel();
        lbl_codm = new javax.swing.JLabel();
        lbl_text_codm = new javax.swing.JLabel();
        lbl_text_genshin = new javax.swing.JLabel();
        lbl_text_ml = new javax.swing.JLabel();
        lbl_text_ff = new javax.swing.JLabel();
        lbl_text_lol = new javax.swing.JLabel();
        lbl_text_valorant = new javax.swing.JLabel();
        lbl_lol = new javax.swing.JLabel();
        lbl_honkai3 = new javax.swing.JLabel();
        lbl_pb = new javax.swing.JLabel();
        lbl_LM = new javax.swing.JLabel();
        lbl_aov = new javax.swing.JLabel();
        lbl_text_honkai3 = new javax.swing.JLabel();
        lbl_text_pb = new javax.swing.JLabel();
        lbl_text_LM = new javax.swing.JLabel();
        lbl_text_ragnarok = new javax.swing.JLabel();
        lbl_text_aov = new javax.swing.JLabel();
        lbl_ragnarok = new javax.swing.JLabel();
        panel_aplikasi = new javax.swing.JScrollPane();
        list_aplikasi = new javax.swing.JPanel();
        lbl_vidio = new javax.swing.JLabel();
        lbl_steam = new javax.swing.JLabel();
        lbl_viu = new javax.swing.JLabel();
        lbl_googleplay = new javax.swing.JLabel();
        lbl_psstore = new javax.swing.JLabel();
        lbl_spotify = new javax.swing.JLabel();
        lbl_text_viu = new javax.swing.JLabel();
        lbl_text_steam = new javax.swing.JLabel();
        lbl_text_psstore = new javax.swing.JLabel();
        lbl_text_spotify = new javax.swing.JLabel();
        lbl_text_googleplay = new javax.swing.JLabel();
        lbl_text_vidio = new javax.swing.JLabel();
        lbl_nintendo = new javax.swing.JLabel();
        lbl_text_nintendo = new javax.swing.JLabel();
        panel_riwayat = new javax.swing.JPanel();
        lbl_riwayat = new javax.swing.JLabel();
        panel_tentang = new javax.swing.JPanel();
        lbl_tentang = new javax.swing.JLabel();
        panel_topup = new javax.swing.JPanel();
        lbl_topup = new javax.swing.JLabel();
        panel_window = new javax.swing.JPanel();
        icon_close = new javax.swing.JLabel();
        icon_minimize = new javax.swing.JLabel();
        panel_logout = new javax.swing.JPanel();
        icon_logout = new javax.swing.JLabel();
        lbl_logout = new javax.swing.JLabel();
        panel_listgames = new javax.swing.JPanel();
        lbl_games = new javax.swing.JLabel();
        panel_listaplikasi = new javax.swing.JPanel();
        lbl_aplikasi = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SkyApp Menu");
        setBackground(new java.awt.Color(0, 195, 217));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 840));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 840));
        getContentPane().setLayout(null);

        panel_utama.setBackground(new java.awt.Color(255, 255, 255));
        panel_utama.setPreferredSize(new java.awt.Dimension(1000, 840));
        panel_utama.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_utamaMouseDragged(evt);
            }
        });
        panel_utama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_utamaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panel_utamaMouseReleased(evt);
            }
        });
        panel_utama.setLayout(null);

        lbl_skyapp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_skyapp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo/LogoFullMenu.png"))); // NOI18N
        panel_utama.add(lbl_skyapp);
        lbl_skyapp.setBounds(0, 60, 220, 150);

        lbl_user.setBackground(new java.awt.Color(255, 255, 255));
        lbl_user.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        lbl_user.setForeground(new java.awt.Color(0, 0, 0));
        lbl_user.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_user.setText("User");
        panel_utama.add(lbl_user);
        lbl_user.setBounds(740, 80, 210, 30);

        lbl_rupiah.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        lbl_rupiah.setForeground(new java.awt.Color(0, 167, 255));
        lbl_rupiah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_rupiah.setText("0");
        panel_utama.add(lbl_rupiah);
        lbl_rupiah.setBounds(660, 140, 290, 30);

        lbl_saldo.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        lbl_saldo.setForeground(new java.awt.Color(0, 167, 255));
        lbl_saldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_saldo.setText("Rp");
        panel_utama.add(lbl_saldo);
        lbl_saldo.setBounds(620, 140, 40, 30);

        icon_coin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_coin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/stack_of_coins_40px.png"))); // NOI18N
        panel_utama.add(icon_coin);
        icon_coin.setBounds(570, 130, 40, 40);

        lbl_selamatdatang.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        lbl_selamatdatang.setForeground(new java.awt.Color(0, 0, 0));
        lbl_selamatdatang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_selamatdatang.setText("Selamat Datang,");
        panel_utama.add(lbl_selamatdatang);
        lbl_selamatdatang.setBounds(570, 80, 170, 30);
        panel_utama.add(separator_saldo);
        separator_saldo.setBounds(570, 170, 380, 10);

        separator_atas.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        panel_utama.add(separator_atas);
        separator_atas.setBounds(0, 60, 1000, 10);

        panel_games.setBackground(new java.awt.Color(51, 204, 255));
        panel_games.setBorder(null);
        panel_games.setForeground(new java.awt.Color(255, 255, 255));
        panel_games.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        panel_games.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_games.setAutoscrolls(true);
        panel_games.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        panel_games.setHorizontalScrollBar(null);
        panel_games.setOpaque(false);
        panel_games.setPreferredSize(new java.awt.Dimension(780, 630));
        panel_games.setViewportView(list_games);

        list_games.setBackground(new java.awt.Color(255, 255, 255));
        list_games.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        list_games.setPreferredSize(new java.awt.Dimension(780, 2000));
        list_games.setLayout(null);

        lbl_genshin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_genshin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannertopup/GenshinImpact.png"))); // NOI18N
        lbl_genshin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_genshin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_genshinMouseClicked(evt);
            }
        });
        list_games.add(lbl_genshin);
        lbl_genshin.setBounds(10, 30, 240, 240);

        lbl_ml.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ml.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannertopup/ml.png"))); // NOI18N
        lbl_ml.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ml.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_mlMouseClicked(evt);
            }
        });
        list_games.add(lbl_ml);
        lbl_ml.setBounds(260, 30, 240, 240);

        lbl_ff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannertopup/FF.png"))); // NOI18N
        lbl_ff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ffMouseClicked(evt);
            }
        });
        list_games.add(lbl_ff);
        lbl_ff.setBounds(510, 30, 240, 240);

        lbl_valorant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_valorant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannertopup/Valorant.png"))); // NOI18N
        lbl_valorant.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_valorant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_valorantMouseClicked(evt);
            }
        });
        list_games.add(lbl_valorant);
        lbl_valorant.setBounds(260, 340, 240, 240);

        lbl_codm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_codm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannertopup/CODM.png"))); // NOI18N
        lbl_codm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_codm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_codmMouseClicked(evt);
            }
        });
        list_games.add(lbl_codm);
        lbl_codm.setBounds(510, 340, 240, 240);

        lbl_text_codm.setBackground(new java.awt.Color(255, 255, 255));
        lbl_text_codm.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbl_text_codm.setForeground(new java.awt.Color(0, 0, 0));
        lbl_text_codm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_codm.setText("COD Mobile");
        lbl_text_codm.setOpaque(true);
        list_games.add(lbl_text_codm);
        lbl_text_codm.setBounds(510, 590, 240, 30);

        lbl_text_genshin.setBackground(new java.awt.Color(255, 255, 255));
        lbl_text_genshin.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbl_text_genshin.setForeground(new java.awt.Color(0, 0, 0));
        lbl_text_genshin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_genshin.setText("Genshin Impact");
        lbl_text_genshin.setOpaque(true);
        list_games.add(lbl_text_genshin);
        lbl_text_genshin.setBounds(10, 280, 240, 30);

        lbl_text_ml.setBackground(new java.awt.Color(255, 255, 255));
        lbl_text_ml.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbl_text_ml.setForeground(new java.awt.Color(0, 0, 0));
        lbl_text_ml.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_ml.setText("Mobile Legends");
        lbl_text_ml.setOpaque(true);
        list_games.add(lbl_text_ml);
        lbl_text_ml.setBounds(260, 280, 240, 30);

        lbl_text_ff.setBackground(new java.awt.Color(255, 255, 255));
        lbl_text_ff.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbl_text_ff.setForeground(new java.awt.Color(0, 0, 0));
        lbl_text_ff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_ff.setText("Free Fire");
        lbl_text_ff.setOpaque(true);
        list_games.add(lbl_text_ff);
        lbl_text_ff.setBounds(510, 280, 240, 30);

        lbl_text_lol.setBackground(new java.awt.Color(255, 255, 255));
        lbl_text_lol.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbl_text_lol.setForeground(new java.awt.Color(0, 0, 0));
        lbl_text_lol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_lol.setText("LoL: Wild Rift");
        lbl_text_lol.setOpaque(true);
        list_games.add(lbl_text_lol);
        lbl_text_lol.setBounds(10, 590, 240, 30);

        lbl_text_valorant.setBackground(new java.awt.Color(255, 255, 255));
        lbl_text_valorant.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbl_text_valorant.setForeground(new java.awt.Color(0, 0, 0));
        lbl_text_valorant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_valorant.setText("Valorant");
        lbl_text_valorant.setOpaque(true);
        list_games.add(lbl_text_valorant);
        lbl_text_valorant.setBounds(260, 590, 240, 30);

        lbl_lol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_lol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannertopup/LoL.png"))); // NOI18N
        lbl_lol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_lol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_lolMouseClicked(evt);
            }
        });
        list_games.add(lbl_lol);
        lbl_lol.setBounds(10, 340, 240, 240);

        lbl_honkai3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_honkai3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannertopup/HI3.png"))); // NOI18N
        lbl_honkai3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_honkai3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_honkai3MouseClicked(evt);
            }
        });
        list_games.add(lbl_honkai3);
        lbl_honkai3.setBounds(10, 650, 240, 240);

        lbl_pb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_pb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannertopup/PB.png"))); // NOI18N
        lbl_pb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_pb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_pbMouseClicked(evt);
            }
        });
        list_games.add(lbl_pb);
        lbl_pb.setBounds(260, 650, 240, 240);

        lbl_LM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_LM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannertopup/LordsMobile.png"))); // NOI18N
        lbl_LM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_LM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_LMMouseClicked(evt);
            }
        });
        list_games.add(lbl_LM);
        lbl_LM.setBounds(510, 650, 240, 240);

        lbl_aov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_aov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannertopup/AOV.png"))); // NOI18N
        lbl_aov.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_aov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_aovMouseClicked(evt);
            }
        });
        list_games.add(lbl_aov);
        lbl_aov.setBounds(260, 960, 240, 240);

        lbl_text_honkai3.setBackground(new java.awt.Color(255, 255, 255));
        lbl_text_honkai3.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbl_text_honkai3.setForeground(new java.awt.Color(0, 0, 0));
        lbl_text_honkai3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_honkai3.setText("Honkai Impact 3");
        lbl_text_honkai3.setOpaque(true);
        list_games.add(lbl_text_honkai3);
        lbl_text_honkai3.setBounds(10, 900, 240, 30);

        lbl_text_pb.setBackground(new java.awt.Color(255, 255, 255));
        lbl_text_pb.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbl_text_pb.setForeground(new java.awt.Color(0, 0, 0));
        lbl_text_pb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_pb.setText("Point Blank");
        lbl_text_pb.setOpaque(true);
        list_games.add(lbl_text_pb);
        lbl_text_pb.setBounds(260, 900, 240, 30);

        lbl_text_LM.setBackground(new java.awt.Color(255, 255, 255));
        lbl_text_LM.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbl_text_LM.setForeground(new java.awt.Color(0, 0, 0));
        lbl_text_LM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_LM.setText("Lords Mobile");
        lbl_text_LM.setOpaque(true);
        list_games.add(lbl_text_LM);
        lbl_text_LM.setBounds(510, 900, 240, 30);

        lbl_text_ragnarok.setBackground(new java.awt.Color(255, 255, 255));
        lbl_text_ragnarok.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbl_text_ragnarok.setForeground(new java.awt.Color(0, 0, 0));
        lbl_text_ragnarok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_ragnarok.setText("Ragnarok M");
        lbl_text_ragnarok.setOpaque(true);
        list_games.add(lbl_text_ragnarok);
        lbl_text_ragnarok.setBounds(10, 1210, 240, 30);

        lbl_text_aov.setBackground(new java.awt.Color(255, 255, 255));
        lbl_text_aov.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbl_text_aov.setForeground(new java.awt.Color(0, 0, 0));
        lbl_text_aov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_aov.setText("ARENA OF VALOR");
        lbl_text_aov.setOpaque(true);
        list_games.add(lbl_text_aov);
        lbl_text_aov.setBounds(260, 1210, 240, 30);

        lbl_ragnarok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ragnarok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannertopup/Ragnarok M.png"))); // NOI18N
        lbl_ragnarok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ragnarok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ragnarokMouseClicked(evt);
            }
        });
        list_games.add(lbl_ragnarok);
        lbl_ragnarok.setBounds(10, 960, 240, 240);

        panel_games.setViewportView(list_games);

        panel_utama.add(panel_games);
        panel_games.setBounds(220, 210, 780, 630);

        panel_aplikasi.setBackground(new java.awt.Color(51, 204, 255));
        panel_aplikasi.setBorder(null);
        panel_aplikasi.setForeground(new java.awt.Color(255, 255, 255));
        panel_aplikasi.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        panel_aplikasi.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_aplikasi.setAutoscrolls(true);
        panel_aplikasi.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        panel_aplikasi.setHorizontalScrollBar(null);
        panel_aplikasi.setOpaque(false);
        panel_aplikasi.setPreferredSize(new java.awt.Dimension(780, 630));
        panel_aplikasi.setViewportView(list_aplikasi);

        list_aplikasi.setBackground(new java.awt.Color(255, 255, 255));
        list_aplikasi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        list_aplikasi.setPreferredSize(new java.awt.Dimension(780, 2000));
        list_aplikasi.setLayout(null);

        lbl_vidio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_vidio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannertopup/vidio.png"))); // NOI18N
        lbl_vidio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_vidio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_vidioMouseClicked(evt);
            }
        });
        list_aplikasi.add(lbl_vidio);
        lbl_vidio.setBounds(510, 30, 240, 240);

        lbl_steam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_steam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannertopup/Steam.png"))); // NOI18N
        lbl_steam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_steam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_steamMouseClicked(evt);
            }
        });
        list_aplikasi.add(lbl_steam);
        lbl_steam.setBounds(0, 650, 250, 240);

        lbl_viu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_viu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannertopup/VIU.png"))); // NOI18N
        lbl_viu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_viu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_viuMouseClicked(evt);
            }
        });
        list_aplikasi.add(lbl_viu);
        lbl_viu.setBounds(510, 340, 240, 240);

        lbl_googleplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_googleplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannertopup/GooglePlay.png"))); // NOI18N
        lbl_googleplay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_googleplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_googleplayMouseClicked(evt);
            }
        });
        list_aplikasi.add(lbl_googleplay);
        lbl_googleplay.setBounds(260, 30, 240, 240);

        lbl_psstore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_psstore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannertopup/PSN_STORE.png"))); // NOI18N
        lbl_psstore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_psstore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_psstoreMouseClicked(evt);
            }
        });
        list_aplikasi.add(lbl_psstore);
        lbl_psstore.setBounds(260, 340, 240, 240);

        lbl_spotify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_spotify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannertopup/Spotify.png"))); // NOI18N
        lbl_spotify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_spotify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_spotifyMouseClicked(evt);
            }
        });
        list_aplikasi.add(lbl_spotify);
        lbl_spotify.setBounds(10, 30, 238, 240);

        lbl_text_viu.setBackground(new java.awt.Color(255, 255, 255));
        lbl_text_viu.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbl_text_viu.setForeground(new java.awt.Color(0, 0, 0));
        lbl_text_viu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_viu.setText("VIU");
        lbl_text_viu.setOpaque(true);
        list_aplikasi.add(lbl_text_viu);
        lbl_text_viu.setBounds(520, 590, 220, 30);

        lbl_text_steam.setBackground(new java.awt.Color(255, 255, 255));
        lbl_text_steam.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbl_text_steam.setForeground(new java.awt.Color(0, 0, 0));
        lbl_text_steam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_steam.setText("STEAM");
        lbl_text_steam.setOpaque(true);
        list_aplikasi.add(lbl_text_steam);
        lbl_text_steam.setBounds(10, 900, 230, 30);

        lbl_text_psstore.setBackground(new java.awt.Color(255, 255, 255));
        lbl_text_psstore.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbl_text_psstore.setForeground(new java.awt.Color(0, 0, 0));
        lbl_text_psstore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_psstore.setText("PlayStation Store");
        lbl_text_psstore.setOpaque(true);
        list_aplikasi.add(lbl_text_psstore);
        lbl_text_psstore.setBounds(260, 590, 240, 30);

        lbl_text_spotify.setBackground(new java.awt.Color(255, 255, 255));
        lbl_text_spotify.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbl_text_spotify.setForeground(new java.awt.Color(0, 0, 0));
        lbl_text_spotify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_spotify.setText("Spotify");
        lbl_text_spotify.setOpaque(true);
        list_aplikasi.add(lbl_text_spotify);
        lbl_text_spotify.setBounds(10, 280, 240, 30);

        lbl_text_googleplay.setBackground(new java.awt.Color(255, 255, 255));
        lbl_text_googleplay.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbl_text_googleplay.setForeground(new java.awt.Color(0, 0, 0));
        lbl_text_googleplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_googleplay.setText("Google Play");
        lbl_text_googleplay.setOpaque(true);
        list_aplikasi.add(lbl_text_googleplay);
        lbl_text_googleplay.setBounds(260, 280, 240, 30);

        lbl_text_vidio.setBackground(new java.awt.Color(255, 255, 255));
        lbl_text_vidio.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbl_text_vidio.setForeground(new java.awt.Color(0, 0, 0));
        lbl_text_vidio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_vidio.setText("Vidio");
        lbl_text_vidio.setOpaque(true);
        list_aplikasi.add(lbl_text_vidio);
        lbl_text_vidio.setBounds(520, 280, 220, 30);

        lbl_nintendo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_nintendo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannertopup/Nintendo_eShop.png"))); // NOI18N
        lbl_nintendo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_nintendo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_nintendoMouseClicked(evt);
            }
        });
        list_aplikasi.add(lbl_nintendo);
        lbl_nintendo.setBounds(10, 340, 240, 240);

        lbl_text_nintendo.setBackground(new java.awt.Color(255, 255, 255));
        lbl_text_nintendo.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbl_text_nintendo.setForeground(new java.awt.Color(0, 0, 0));
        lbl_text_nintendo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_nintendo.setText("Nintendo eShop");
        lbl_text_nintendo.setOpaque(true);
        list_aplikasi.add(lbl_text_nintendo);
        lbl_text_nintendo.setBounds(10, 590, 240, 30);

        panel_aplikasi.setViewportView(list_aplikasi);

        panel_utama.add(panel_aplikasi);
        panel_aplikasi.setBounds(220, 210, 780, 630);

        panel_riwayat.setBackground(new java.awt.Color(0, 167, 255));
        panel_riwayat.setLayout(null);

        lbl_riwayat.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lbl_riwayat.setForeground(new java.awt.Color(255, 255, 255));
        lbl_riwayat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_riwayat.setText("RIWAYAT PEMBELIAN");
        lbl_riwayat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_riwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_riwayatMouseClicked(evt);
            }
        });
        panel_riwayat.add(lbl_riwayat);
        lbl_riwayat.setBounds(0, 0, 260, 60);

        panel_utama.add(panel_riwayat);
        panel_riwayat.setBounds(220, 0, 260, 60);

        panel_tentang.setBackground(new java.awt.Color(0, 167, 255));
        panel_tentang.setLayout(null);

        lbl_tentang.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lbl_tentang.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tentang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tentang.setText("TENTANG KAMI");
        lbl_tentang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_tentang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_tentangMouseClicked(evt);
            }
        });
        panel_tentang.add(lbl_tentang);
        lbl_tentang.setBounds(0, 0, 230, 60);

        panel_utama.add(panel_tentang);
        panel_tentang.setBounds(480, 0, 230, 60);

        panel_topup.setBackground(new java.awt.Color(0, 167, 255));
        panel_topup.setLayout(null);

        lbl_topup.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lbl_topup.setForeground(new java.awt.Color(255, 255, 255));
        lbl_topup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_topup.setText("TOPUP SALDO");
        lbl_topup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_topup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_topupMouseClicked(evt);
            }
        });
        panel_topup.add(lbl_topup);
        lbl_topup.setBounds(0, 0, 220, 60);

        panel_utama.add(panel_topup);
        panel_topup.setBounds(0, 0, 220, 60);

        panel_window.setBackground(new java.awt.Color(0, 167, 255));
        panel_window.setLayout(null);

        icon_close.setFont(new java.awt.Font("Poppins SemiBold", 1, 36)); // NOI18N
        icon_close.setForeground(new java.awt.Color(255, 255, 255));
        icon_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/multiply_40px_white.png"))); // NOI18N
        icon_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_closeMouseClicked(evt);
            }
        });
        panel_window.add(icon_close);
        icon_close.setBounds(240, 10, 30, 50);

        icon_minimize.setFont(new java.awt.Font("Poppins SemiBold", 1, 48)); // NOI18N
        icon_minimize.setForeground(new java.awt.Color(255, 255, 255));
        icon_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/subtract_40px_white.png"))); // NOI18N
        icon_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_minimizeMouseClicked(evt);
            }
        });
        panel_window.add(icon_minimize);
        icon_minimize.setBounds(170, 20, 50, 30);

        panel_utama.add(panel_window);
        panel_window.setBounds(710, 0, 290, 60);

        panel_logout.setBackground(new java.awt.Color(0, 167, 255));
        panel_logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_logoutMouseClicked(evt);
            }
        });
        panel_logout.setLayout(null);

        icon_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/exit_80px.png"))); // NOI18N
        panel_logout.add(icon_logout);
        icon_logout.setBounds(0, 20, 220, 110);

        lbl_logout.setFont(new java.awt.Font("Poppins Black", 0, 36)); // NOI18N
        lbl_logout.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logout.setText("LOG OUT");
        panel_logout.add(lbl_logout);
        lbl_logout.setBounds(0, 120, 220, 90);

        panel_utama.add(panel_logout);
        panel_logout.setBounds(0, 630, 220, 210);

        panel_listgames.setBackground(new java.awt.Color(0, 167, 255));
        panel_listgames.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_listgames.setLayout(null);

        lbl_games.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        lbl_games.setForeground(new java.awt.Color(255, 255, 255));
        lbl_games.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_games.setText("GAMES");
        lbl_games.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_games.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_gamesMouseClicked(evt);
            }
        });
        panel_listgames.add(lbl_games);
        lbl_games.setBounds(1, 1, 218, 208);

        panel_utama.add(panel_listgames);
        panel_listgames.setBounds(0, 210, 220, 210);

        panel_listaplikasi.setBackground(new java.awt.Color(0, 167, 255));
        panel_listaplikasi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_listaplikasi.setLayout(null);

        lbl_aplikasi.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        lbl_aplikasi.setForeground(new java.awt.Color(255, 255, 255));
        lbl_aplikasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_aplikasi.setText("APLIKASI");
        lbl_aplikasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_aplikasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_aplikasiMouseClicked(evt);
            }
        });
        panel_listaplikasi.add(lbl_aplikasi);
        lbl_aplikasi.setBounds(1, 1, 218, 208);

        panel_utama.add(panel_listaplikasi);
        panel_listaplikasi.setBounds(0, 420, 220, 210);
        panel_utama.add(jSeparator1);
        jSeparator1.setBounds(0, 207, 1000, 3);

        getContentPane().add(panel_utama);
        panel_utama.setBounds(0, 0, 1000, 840);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_mlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_mlMouseClicked
        ML ML = new ML(this.user);
        
        ML.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_mlMouseClicked

    private void lbl_genshinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_genshinMouseClicked
        GI GI = new GI(this.user);
        
        GI.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_genshinMouseClicked

    private void lbl_ffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ffMouseClicked
        FF FF = new FF(this.user);
        
        FF.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_ffMouseClicked

    private void lbl_valorantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_valorantMouseClicked
        Valorant valo = new Valorant(this.user);
        
        valo.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_valorantMouseClicked

    private void lbl_codmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_codmMouseClicked
        CODM CODM = new CODM(this.user);
        
        CODM.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_codmMouseClicked

    private void lbl_vidioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_vidioMouseClicked
        VID VID = new VID(this.user);
        
        VID.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_vidioMouseClicked

    private void lbl_steamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_steamMouseClicked
        STEAM ST = new STEAM(this.user);
        
        ST.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_steamMouseClicked

    private void lbl_viuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viuMouseClicked
        VIU VIU = new VIU(this.user);
        
        VIU.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_viuMouseClicked

    private void lbl_googleplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_googleplayMouseClicked
        GOP GOP = new GOP(this.user);
        
        GOP.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_googleplayMouseClicked

    private void lbl_psstoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_psstoreMouseClicked
        PST PST = new PST(this.user);
        
        PST.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_psstoreMouseClicked

    private void lbl_spotifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_spotifyMouseClicked
        SPT SPT = new SPT(this.user);
        
        SPT.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_spotifyMouseClicked

    private void panel_utamaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_utamaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panel_utamaMousePressed

    private void panel_utamaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_utamaMouseDragged
        panel_utama.setCursor(Cursor.getPredefinedCursor(Cursor.MOVE_CURSOR));
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panel_utamaMouseDragged

    private void icon_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_icon_closeMouseClicked

    private void icon_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_minimizeMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_icon_minimizeMouseClicked

    private void lbl_topupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_topupMouseClicked
        TopUp tp = new TopUp(this.user);
        
        tp.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_topupMouseClicked

    private void lbl_tentangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_tentangMouseClicked
        TentangKami tk = new TentangKami();
        
        tk.setVisible(true);
        tk.toFront();
        this.toBack();
    }//GEN-LAST:event_lbl_tentangMouseClicked

    private void lbl_riwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_riwayatMouseClicked
        Riwayat rt = new Riwayat(this.user);
        
        rt.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_riwayatMouseClicked

    private void lbl_gamesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_gamesMouseClicked
       panel_aplikasi.setVisible(false);
       panel_games.setVisible(true);
    }//GEN-LAST:event_lbl_gamesMouseClicked

    private void lbl_aplikasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_aplikasiMouseClicked
       panel_games.setVisible(false);
       panel_aplikasi.setVisible(true);
    }//GEN-LAST:event_lbl_aplikasiMouseClicked

    private void panel_utamaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_utamaMouseReleased
        panel_utama.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_panel_utamaMouseReleased

    private void panel_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_logoutMouseClicked
        Login lg = new Login();
        
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_panel_logoutMouseClicked

    private void lbl_lolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_lolMouseClicked
        LOL LOL = new LOL(this.user);
        
        LOL.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_lolMouseClicked

    private void lbl_honkai3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_honkai3MouseClicked
        HONKAI HK = new HONKAI(this.user);
        
        HK.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_honkai3MouseClicked

    private void lbl_pbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pbMouseClicked
        PB PB = new PB(this.user);
        
        PB.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_pbMouseClicked

    private void lbl_LMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LMMouseClicked
        LM LM = new LM(this.user);
        
        LM.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_LMMouseClicked

    private void lbl_aovMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_aovMouseClicked
        AOV AOV = new AOV(this.user);
        
        AOV.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_aovMouseClicked

    private void lbl_ragnarokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ragnarokMouseClicked
        RAGNA RR = new RAGNA(this.user);
        
        RR.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_ragnarokMouseClicked

    private void lbl_nintendoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_nintendoMouseClicked
        TEN TEN = new TEN(this.user);
        
        TEN.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_nintendoMouseClicked

    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon_close;
    private javax.swing.JLabel icon_coin;
    private javax.swing.JLabel icon_logout;
    private javax.swing.JLabel icon_minimize;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_LM;
    private javax.swing.JLabel lbl_aov;
    private javax.swing.JLabel lbl_aplikasi;
    private javax.swing.JLabel lbl_codm;
    private javax.swing.JLabel lbl_ff;
    private javax.swing.JLabel lbl_games;
    private javax.swing.JLabel lbl_genshin;
    private javax.swing.JLabel lbl_googleplay;
    private javax.swing.JLabel lbl_honkai3;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JLabel lbl_lol;
    private javax.swing.JLabel lbl_ml;
    private javax.swing.JLabel lbl_nintendo;
    private javax.swing.JLabel lbl_pb;
    private javax.swing.JLabel lbl_psstore;
    private javax.swing.JLabel lbl_ragnarok;
    private javax.swing.JLabel lbl_riwayat;
    static javax.swing.JLabel lbl_rupiah;
    private javax.swing.JLabel lbl_saldo;
    private javax.swing.JLabel lbl_selamatdatang;
    private javax.swing.JLabel lbl_skyapp;
    private javax.swing.JLabel lbl_spotify;
    private javax.swing.JLabel lbl_steam;
    private javax.swing.JLabel lbl_tentang;
    private javax.swing.JLabel lbl_text_LM;
    private javax.swing.JLabel lbl_text_aov;
    private javax.swing.JLabel lbl_text_codm;
    private javax.swing.JLabel lbl_text_ff;
    private javax.swing.JLabel lbl_text_genshin;
    private javax.swing.JLabel lbl_text_googleplay;
    private javax.swing.JLabel lbl_text_honkai3;
    private javax.swing.JLabel lbl_text_lol;
    private javax.swing.JLabel lbl_text_ml;
    private javax.swing.JLabel lbl_text_nintendo;
    private javax.swing.JLabel lbl_text_pb;
    private javax.swing.JLabel lbl_text_psstore;
    private javax.swing.JLabel lbl_text_ragnarok;
    private javax.swing.JLabel lbl_text_spotify;
    private javax.swing.JLabel lbl_text_steam;
    private javax.swing.JLabel lbl_text_valorant;
    private javax.swing.JLabel lbl_text_vidio;
    private javax.swing.JLabel lbl_text_viu;
    private javax.swing.JLabel lbl_topup;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JLabel lbl_valorant;
    private javax.swing.JLabel lbl_vidio;
    private javax.swing.JLabel lbl_viu;
    private javax.swing.JPanel list_aplikasi;
    private javax.swing.JPanel list_games;
    private javax.swing.JScrollPane panel_aplikasi;
    private javax.swing.JScrollPane panel_games;
    private javax.swing.JPanel panel_listaplikasi;
    private javax.swing.JPanel panel_listgames;
    private javax.swing.JPanel panel_logout;
    private javax.swing.JPanel panel_riwayat;
    private javax.swing.JPanel panel_tentang;
    private javax.swing.JPanel panel_topup;
    private javax.swing.JPanel panel_utama;
    private javax.swing.JPanel panel_window;
    private javax.swing.JSeparator separator_atas;
    private javax.swing.JSeparator separator_saldo;
    // End of variables declaration//GEN-END:variables
}
