/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skyapp;

import cek_validasi.EmptyValidation;
import database.User;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Kelompok 1 (TI 2020 C)
 */
public class Register extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    
    public Register() {
        this.setIconImage(new ImageIcon("src//images//logo//Logo.png").getImage());
        initComponents();
        this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon_close = new javax.swing.JLabel();
        icon_minimize = new javax.swing.JLabel();
        panel_register = new javax.swing.JPanel();
        lbl_signup = new javax.swing.JLabel();
        lbl_pindah_login = new javax.swing.JLabel();
        txt_email_signup = new javax.swing.JTextField();
        txt_username_signup = new javax.swing.JTextField();
        txt_password_signup = new javax.swing.JPasswordField();
        panel_gambarRegister = new javax.swing.JPanel();
        lbl_gambar1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SkyApp Register");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 800));
        getContentPane().setLayout(null);

        icon_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_closeMouseClicked(evt);
            }
        });
        getContentPane().add(icon_close);
        icon_close.setBounds(460, 10, 30, 40);

        icon_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(icon_minimize);
        icon_minimize.setBounds(410, 20, 30, 20);

        panel_register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        panel_register.setLayout(null);

        lbl_signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_signupMouseClicked(evt);
            }
        });
        panel_register.add(lbl_signup);
        lbl_signup.setBounds(300, 620, 120, 100);

        lbl_pindah_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_pindah_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_pindah_loginMouseClicked(evt);
            }
        });
        panel_register.add(lbl_pindah_login);
        lbl_pindah_login.setBounds(100, 620, 110, 100);

        txt_email_signup.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        txt_email_signup.setForeground(new java.awt.Color(54, 64, 77));
        txt_email_signup.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_email_signup.setText("email");
        txt_email_signup.setBorder(null);
        txt_email_signup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_email_signupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_email_signupFocusLost(evt);
            }
        });
        txt_email_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_email_signupActionPerformed(evt);
            }
        });
        panel_register.add(txt_email_signup);
        txt_email_signup.setBounds(150, 390, 230, 25);

        txt_username_signup.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        txt_username_signup.setForeground(new java.awt.Color(54, 64, 77));
        txt_username_signup.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_username_signup.setText("username");
        txt_username_signup.setBorder(null);
        txt_username_signup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_username_signupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_username_signupFocusLost(evt);
            }
        });
        panel_register.add(txt_username_signup);
        txt_username_signup.setBounds(150, 450, 230, 25);

        txt_password_signup.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        txt_password_signup.setForeground(new java.awt.Color(54, 64, 77));
        txt_password_signup.setText("Password");
        txt_password_signup.setBorder(null);
        txt_password_signup.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_password_signup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_password_signupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_password_signupFocusLost(evt);
            }
        });
        panel_register.add(txt_password_signup);
        txt_password_signup.setBounds(150, 510, 230, 24);

        panel_gambarRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_gambarRegister.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_gambarRegisterMouseDragged(evt);
            }
        });
        panel_gambarRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_gambarRegisterMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panel_gambarRegisterMouseReleased(evt);
            }
        });
        panel_gambarRegister.setLayout(null);

        lbl_gambar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_gambar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page/Register.png"))); // NOI18N
        lbl_gambar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel_gambarRegister.add(lbl_gambar1);
        lbl_gambar1.setBounds(0, 0, 500, 800);

        panel_register.add(panel_gambarRegister);
        panel_gambarRegister.setBounds(0, 0, 500, 800);

        getContentPane().add(panel_register);
        panel_register.setBounds(0, 0, 500, 800);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_signupMouseClicked
        String cek = EmptyValidation.cekRegistrasi(txt_email_signup, txt_username_signup, txt_password_signup);

        if(cek.equals("valid")) {
            String email = txt_email_signup.getText();
            String username = txt_username_signup.getText();
            String password = new String(txt_password_signup.getPassword());
            String simpan = new User().tambah_user(email,username,password);
            JOptionPane.showMessageDialog(null,simpan);

            Login lg = new Login();

            this.setVisible(false);
            lg.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, cek);
        }
    }//GEN-LAST:event_lbl_signupMouseClicked

    private void lbl_pindah_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pindah_loginMouseClicked
        Login lg = new Login();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_pindah_loginMouseClicked

    private void txt_email_signupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_email_signupFocusGained
        if(txt_email_signup.getText().equals("email")){
            txt_email_signup.setText("");
        }

        txt_email_signup.setForeground(new Color(54, 64, 77));
    }//GEN-LAST:event_txt_email_signupFocusGained

    private void txt_email_signupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_email_signupFocusLost
        if(txt_email_signup.getText().equals("")){
            txt_email_signup.setText("email");
        }

        txt_email_signup.setForeground(new Color(54, 64, 77));
    }//GEN-LAST:event_txt_email_signupFocusLost

    private void txt_username_signupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_username_signupFocusGained
        if(txt_username_signup.getText().equals("username")){
            txt_username_signup.setText("");
        }

        txt_username_signup.setForeground(new Color(54, 64, 77));
    }//GEN-LAST:event_txt_username_signupFocusGained

    private void txt_username_signupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_username_signupFocusLost
        if(txt_username_signup.getText().equals("")){
            txt_username_signup.setText("username");
        }

        txt_username_signup.setForeground(new Color(54, 64, 77));
    }//GEN-LAST:event_txt_username_signupFocusLost

    private void txt_password_signupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_password_signupFocusGained
        if(new String (txt_password_signup.getPassword()).equals("Password")){
            txt_password_signup.setText("");
        }

        txt_password_signup.setForeground(new Color(54, 64, 77));
    }//GEN-LAST:event_txt_password_signupFocusGained

    private void txt_password_signupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_password_signupFocusLost
        if(new String (txt_password_signup.getPassword()).equals("")){
            txt_password_signup.setText("Password");
        }

        txt_password_signup.setForeground(new Color(54,64, 77));
    }//GEN-LAST:event_txt_password_signupFocusLost

    private void panel_gambarRegisterMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_gambarRegisterMouseDragged
        panel_gambarRegister.setCursor(Cursor.getPredefinedCursor(Cursor.MOVE_CURSOR));
        
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panel_gambarRegisterMouseDragged

    private void panel_gambarRegisterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_gambarRegisterMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panel_gambarRegisterMousePressed

    private void icon_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_icon_closeMouseClicked

    private void icon_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_minimizeMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_icon_minimizeMouseClicked

    private void panel_gambarRegisterMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_gambarRegisterMouseReleased
        panel_gambarRegister.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_panel_gambarRegisterMouseReleased

    private void txt_email_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_email_signupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_email_signupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon_close;
    private javax.swing.JLabel icon_minimize;
    private javax.swing.JLabel lbl_gambar1;
    private javax.swing.JLabel lbl_pindah_login;
    private javax.swing.JLabel lbl_signup;
    private javax.swing.JPanel panel_gambarRegister;
    private javax.swing.JPanel panel_register;
    private javax.swing.JTextField txt_email_signup;
    private javax.swing.JPasswordField txt_password_signup;
    private javax.swing.JTextField txt_username_signup;
    // End of variables declaration//GEN-END:variables
}
