/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skyapp;

import cek_validasi.EmptyValidation;
import database.User;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Kelompok 1 (TI 2020 C)
 */
public class Reset extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    
    public Reset() {
        this.setIconImage(new ImageIcon("src//images//logo//Logo.png").getImage());
        initComponents();
        this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_pindah_login = new javax.swing.JLabel();
        lbl_reset = new javax.swing.JLabel();
        icon_minimize = new javax.swing.JLabel();
        icon_close = new javax.swing.JLabel();
        txt_username_reset = new javax.swing.JTextField();
        txt_password_reset = new javax.swing.JPasswordField();
        txt_password_val = new javax.swing.JPasswordField();
        panel_gambar = new javax.swing.JPanel();
        lbl_gambar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SkyApp Reset");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 800));
        getContentPane().setLayout(null);

        lbl_pindah_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_pindah_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_pindah_loginMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_pindah_login);
        lbl_pindah_login.setBounds(100, 620, 110, 100);

        lbl_reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_resetMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_reset);
        lbl_reset.setBounds(300, 620, 120, 100);

        icon_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(icon_minimize);
        icon_minimize.setBounds(410, 20, 30, 20);

        icon_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_closeMouseClicked(evt);
            }
        });
        getContentPane().add(icon_close);
        icon_close.setBounds(460, 10, 30, 40);

        txt_username_reset.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        txt_username_reset.setForeground(new java.awt.Color(54, 64, 77));
        txt_username_reset.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_username_reset.setText("username");
        txt_username_reset.setBorder(null);
        txt_username_reset.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_username_resetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_username_resetFocusLost(evt);
            }
        });
        getContentPane().add(txt_username_reset);
        txt_username_reset.setBounds(150, 390, 230, 25);

        txt_password_reset.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        txt_password_reset.setForeground(new java.awt.Color(54, 64, 77));
        txt_password_reset.setText("Password");
        txt_password_reset.setBorder(null);
        txt_password_reset.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_password_reset.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_password_resetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_password_resetFocusLost(evt);
            }
        });
        getContentPane().add(txt_password_reset);
        txt_password_reset.setBounds(150, 450, 230, 24);

        txt_password_val.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        txt_password_val.setForeground(new java.awt.Color(54, 64, 77));
        txt_password_val.setText("Password");
        txt_password_val.setBorder(null);
        txt_password_val.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_password_val.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_password_valFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_password_valFocusLost(evt);
            }
        });
        txt_password_val.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_password_valActionPerformed(evt);
            }
        });
        getContentPane().add(txt_password_val);
        txt_password_val.setBounds(150, 510, 230, 20);

        panel_gambar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_gambarMouseDragged(evt);
            }
        });
        panel_gambar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_gambarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panel_gambarMouseReleased(evt);
            }
        });
        panel_gambar.setLayout(null);

        lbl_gambar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page/Reset.png"))); // NOI18N
        lbl_gambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel_gambar.add(lbl_gambar);
        lbl_gambar.setBounds(0, 0, 500, 800);

        getContentPane().add(panel_gambar);
        panel_gambar.setBounds(0, 0, 500, 800);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void icon_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_icon_closeMouseClicked

    private void icon_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_minimizeMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_icon_minimizeMouseClicked

    private void lbl_pindah_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pindah_loginMouseClicked
        Login lg = new Login();

        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_pindah_loginMouseClicked

    private void txt_username_resetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_username_resetFocusGained
        if(txt_username_reset.getText().equals("username")){
            txt_username_reset.setText("");
        }

        txt_username_reset.setForeground(new Color (54, 64, 77));
    }//GEN-LAST:event_txt_username_resetFocusGained

    private void txt_username_resetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_username_resetFocusLost
        if(txt_username_reset.getText().equals("")){
            txt_username_reset.setText("username");
        }

        txt_username_reset.setForeground(new Color(54, 64, 77));
    }//GEN-LAST:event_txt_username_resetFocusLost

    private void txt_password_resetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_password_resetFocusGained
        if(new String (txt_password_reset.getPassword()).equals("Password")){
            txt_password_reset.setText("");
        }

        txt_password_reset.setForeground(new Color(54, 64, 77));
    }//GEN-LAST:event_txt_password_resetFocusGained

    private void txt_password_resetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_password_resetFocusLost
        if(new String (txt_password_reset.getPassword()).equals("")){
            txt_password_reset.setText("Password");
        }

        txt_password_reset.setForeground(new Color(54,64, 77));
    }//GEN-LAST:event_txt_password_resetFocusLost

    private void txt_password_valFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_password_valFocusGained
        if(new String (txt_password_val.getPassword()).equals("Password")){
            txt_password_val.setText("");
        }

        txt_password_val.setForeground(new Color(54, 64, 77));
    }//GEN-LAST:event_txt_password_valFocusGained

    private void txt_password_valFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_password_valFocusLost
        if(new String (txt_password_val.getPassword()).equals("")){
            txt_password_val.setText("Password");
        }

        txt_password_val.setForeground(new Color(54, 64, 77));
    }//GEN-LAST:event_txt_password_valFocusLost

    private void txt_password_valActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_password_valActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_password_valActionPerformed

    private void panel_gambarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_gambarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panel_gambarMousePressed

    private void panel_gambarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_gambarMouseDragged
       panel_gambar.setCursor(Cursor.getPredefinedCursor(Cursor.MOVE_CURSOR));
       
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();

       this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panel_gambarMouseDragged

    private void panel_gambarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_gambarMouseReleased
       panel_gambar.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_panel_gambarMouseReleased

    private void lbl_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_resetMouseClicked
    String cek = EmptyValidation.cekReset(txt_username_reset, txt_password_reset, txt_password_val);

        if(cek.equals("valid")) {
            String username = txt_username_reset.getText();
            String password = new String(txt_password_reset.getPassword());
            
            String simpan = new User().update_user(username, password);       
            JOptionPane.showMessageDialog(null,"RESET BERHASIL", "BERHASIL", JOptionPane.INFORMATION_MESSAGE);
            
            Login lg = new Login();     
            lg.setVisible(true);
            dispose();
            
        } else {
            JOptionPane.showMessageDialog(null, cek);
        } 
    }//GEN-LAST:event_lbl_resetMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon_close;
    private javax.swing.JLabel icon_minimize;
    private javax.swing.JLabel lbl_gambar;
    private javax.swing.JLabel lbl_pindah_login;
    private javax.swing.JLabel lbl_reset;
    private javax.swing.JPanel panel_gambar;
    private javax.swing.JPasswordField txt_password_reset;
    private javax.swing.JPasswordField txt_password_val;
    private javax.swing.JTextField txt_username_reset;
    // End of variables declaration//GEN-END:variables
}
