/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skyapp;


import database.Transaksi;
import java.awt.Cursor;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Kelompok 1 (TI 2020 C)
 */
public class Riwayat extends javax.swing.JFrame {
    public String user;
    DefaultTableModel defaultTableModel;
    
    int xMouse;
    int yMouse;

    public Riwayat(String user) {
        this.setIconImage(new ImageIcon("src//images//logo//Logo.png").getImage());
        
        String[] kolom = {"TANGGAL", "KODE PEMBAYARAN", "ID", "JENIS TOPUP", "HARGA", "SISA SALDO"};
        defaultTableModel = new DefaultTableModel(kolom, 0)   {
            //supaya tidak bisa diedit tabelnya
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        
        initComponents();
        
        this.user = user;
          
        tbl_riwayat = new JTable(defaultTableModel);
        
        for(int i = 0;i < tbl_riwayat.getColumnCount();i++) {
            tbl_riwayat.getColumnModel().getColumn(i).setResizable(false);
        }

        tbl_riwayat.getColumnModel().getColumn(0).setPreferredWidth(150);
        tbl_riwayat.getColumnModel().getColumn(1).setPreferredWidth(180);
        tbl_riwayat.getColumnModel().getColumn(2).setPreferredWidth(80);
        tbl_riwayat.getColumnModel().getColumn(3).setPreferredWidth(200);
        tbl_riwayat.getColumnModel().getColumn(4).setPreferredWidth(50);
        tbl_riwayat.getColumnModel().getColumn(5).setPreferredWidth(50);
        
        kosong_tabel();
        tampil_data();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_back = new javax.swing.JLabel();
        lbl_judul = new javax.swing.JLabel();
        sp_riwayat = new javax.swing.JScrollPane();
        tbl_riwayat = new javax.swing.JTable();
        panel_gambar = new javax.swing.JPanel();
        lbl_gambar = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RIWAYAT PEMBELIAN");
        setBackground(new java.awt.Color(102, 255, 255));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        lbl_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/back_40px.png"))); // NOI18N
        lbl_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_back);
        lbl_back.setBounds(10, 10, 40, 40);

        lbl_judul.setFont(new java.awt.Font("Poppins ExtraBold", 0, 36)); // NOI18N
        lbl_judul.setForeground(new java.awt.Color(255, 255, 255));
        lbl_judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_judul.setText("RIWAYAT PEMBELIAN");
        getContentPane().add(lbl_judul);
        lbl_judul.setBounds(160, 40, 480, 30);

        tbl_riwayat.setModel(defaultTableModel);
        tbl_riwayat.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbl_riwayat.getTableHeader().setResizingAllowed(false);
        tbl_riwayat.getTableHeader().setReorderingAllowed(false);
        sp_riwayat.setViewportView(tbl_riwayat);

        getContentPane().add(sp_riwayat);
        sp_riwayat.setBounds(20, 120, 760, 300);

        panel_gambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel_gambar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_gambarMouseDragged(evt);
            }
        });
        panel_gambar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_gambarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panel_gambarMouseReleased(evt);
            }
        });
        panel_gambar.setLayout(null);

        lbl_gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page/riwayat.png"))); // NOI18N
        lbl_gambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel_gambar.add(lbl_gambar);
        lbl_gambar.setBounds(0, 0, 800, 500);
        panel_gambar.add(lbl_user);
        lbl_user.setBounds(80, 340, 0, 0);

        getContentPane().add(panel_gambar);
        panel_gambar.setBounds(0, 0, 800, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
        Menu Menu = new Menu(this.user);
        
        this.setVisible(false);
        Menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_backMouseClicked

    private void panel_gambarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_gambarMouseReleased
        panel_gambar.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_panel_gambarMouseReleased

    private void panel_gambarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_gambarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panel_gambarMousePressed

    private void panel_gambarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_gambarMouseDragged
       panel_gambar.setCursor(Cursor.getPredefinedCursor(Cursor.MOVE_CURSOR));
       
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();

       this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panel_gambarMouseDragged

   public void kosong_tabel() {
       int baris = defaultTableModel.getRowCount();
       for(int i = 0; i < baris; i++) {
           defaultTableModel.removeRow(0);
       }
   }
    
   public void tampil_data() {
        List<Object> data = new Transaksi().get_transaksi(this.user);
        Object[] sl = data.toArray(); // sl[6]
        
        for(int i = 0; i < sl.length; i = i+6) {
        Object[] df = {sl[i], sl[i+1], sl[i+2], sl[i+3], sl[i+4], sl[i+5]};
        defaultTableModel.addRow(df);
        }
       
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_gambar;
    private javax.swing.JLabel lbl_judul;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JPanel panel_gambar;
    private javax.swing.JScrollPane sp_riwayat;
    private javax.swing.JTable tbl_riwayat;
    // End of variables declaration//GEN-END:variables
}
