/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skyapp;

import java.awt.Cursor;
import javax.swing.ImageIcon;

/**
 *
 * @author Kelompok 1 (TI 2020 C)
 */
public class TentangKami extends javax.swing.JFrame {
      int xMouse;
      int yMouse;

    public TentangKami() {
        this.setIconImage(new ImageIcon("src//images//logo//Logo.png").getImage());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon_close = new javax.swing.JLabel();
        icon_minimize = new javax.swing.JLabel();
        panel_tentang = new javax.swing.JPanel();
        lbl_tentang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TENTANG KAMI");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 850));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 850));
        getContentPane().setLayout(null);

        icon_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_closeMouseClicked(evt);
            }
        });
        getContentPane().add(icon_close);
        icon_close.setBounds(460, 10, 30, 40);

        icon_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(icon_minimize);
        icon_minimize.setBounds(410, 10, 40, 30);

        panel_tentang.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_tentangMouseDragged(evt);
            }
        });
        panel_tentang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_tentangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panel_tentangMouseReleased(evt);
            }
        });
        panel_tentang.setLayout(null);

        lbl_tentang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page/TentangKami.png"))); // NOI18N
        lbl_tentang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lbl_tentang.setPreferredSize(new java.awt.Dimension(500, 850));
        panel_tentang.add(lbl_tentang);
        lbl_tentang.setBounds(0, 0, 500, 850);

        getContentPane().add(panel_tentang);
        panel_tentang.setBounds(0, 0, 500, 850);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void icon_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_closeMouseClicked
        this.toBack();
        dispose();
    }//GEN-LAST:event_icon_closeMouseClicked

    private void icon_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_minimizeMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_icon_minimizeMouseClicked

    private void panel_tentangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_tentangMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panel_tentangMousePressed

    private void panel_tentangMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_tentangMouseDragged
       panel_tentang.setCursor(Cursor.getPredefinedCursor(Cursor.MOVE_CURSOR));
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();

       this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panel_tentangMouseDragged

    private void panel_tentangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_tentangMouseReleased
        panel_tentang.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_panel_tentangMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon_close;
    private javax.swing.JLabel icon_minimize;
    private javax.swing.JLabel lbl_tentang;
    private javax.swing.JPanel panel_tentang;
    // End of variables declaration//GEN-END:variables
}
