/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skyapp;

import cek_validasi.EmptyValidation;
import database.Transaksi;
import java.awt.Color;
import java.awt.Cursor;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Kelompok 1 (TI 2020 C)
 */
public class TopUp extends javax.swing.JFrame {
    int xMouse;
    int yMouse;
    
    public String harga;
    public int saldo;
    
    public String user;
    
    String username, id, kode_pembayaran, jenis_topup; 
    SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy");
    int hargadb, sisa_saldo;
    
    public TopUp(String user) {
        this.setIconImage(new ImageIcon("src//images//logo//Logo.png").getImage());
        this.user = user;
               
        initComponents();
        cb_nominal.setBackground(new Color(0,0,0,0));
        
        cb_pembayaran.setBackground(new Color(0,0,0,0));
        
        Transaksi.set_rupiah(user, lbl_rupiah);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_nominal = new javax.swing.JComboBox<>();
        lbl_back = new javax.swing.JLabel();
        lbl_bayar = new javax.swing.JLabel();
        cb_pembayaran = new javax.swing.JComboBox<>();
        lbl_rupiah = new javax.swing.JLabel();
        lempar_user = new javax.swing.JLabel();
        panel_gambarTopup = new javax.swing.JPanel();
        lbl_gambar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TOPUP SALDO");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        cb_nominal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------Pilih Nominal--------", "50000", "100000", "150000", "200000", "300000", "400000", "500000", "600000", "700000", "800000", "900000", "1000000" }));
        cb_nominal.setBorder(null);
        cb_nominal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cb_nominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_nominalActionPerformed(evt);
            }
        });
        getContentPane().add(cb_nominal);
        cb_nominal.setBounds(280, 270, 240, 30);

        lbl_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_back);
        lbl_back.setBounds(10, 10, 50, 40);

        lbl_bayar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_bayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_bayarMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_bayar);
        lbl_bayar.setBounds(254, 504, 100, 40);

        cb_pembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----Pilih Pembayaran-----", "OVO", "DANA", "GOPAY", "UINPAY" }));
        cb_pembayaran.setBorder(null);
        cb_pembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cb_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_pembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(cb_pembayaran);
        cb_pembayaran.setBounds(280, 330, 240, 30);

        lbl_rupiah.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        lbl_rupiah.setForeground(new java.awt.Color(0, 167, 255));
        lbl_rupiah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_rupiah.setText("0");
        getContentPane().add(lbl_rupiah);
        lbl_rupiah.setBounds(420, 20, 170, 37);

        lempar_user.setBackground(new java.awt.Color(255, 255, 255));
        lempar_user.setForeground(new java.awt.Color(255, 255, 255));
        lempar_user.setText("jLabel1");
        getContentPane().add(lempar_user);
        lempar_user.setBounds(70, 420, 41, 18);

        panel_gambarTopup.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_gambarTopupMouseDragged(evt);
            }
        });
        panel_gambarTopup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_gambarTopupMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panel_gambarTopupMouseReleased(evt);
            }
        });
        panel_gambarTopup.setLayout(null);

        lbl_gambar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page/FrameTopupSaldo.png"))); // NOI18N
        lbl_gambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel_gambarTopup.add(lbl_gambar);
        lbl_gambar.setBounds(0, 0, 600, 600);

        getContentPane().add(panel_gambarTopup);
        panel_gambarTopup.setBounds(0, 0, 600, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void set_data() {
        username = this.user;
        
        id = username;
        
        kode_pembayaran = Transaksi.randomToken().toString().replaceAll("([^A-Z0-9]+)", "");
     
        jenis_topup = cb_pembayaran.getSelectedItem().toString() + "-SALDO";
        
        hargadb = Integer.parseInt(this.harga);
        sisa_saldo = Integer.parseInt(lbl_rupiah.getText().trim());
    }
    
    void isEnter (JLabel btn) {
        btn.setBackground(new Color(9, 50, 236));
    }
    
    void isExit (JLabel btn) {
        btn.setBackground(new Color(0, 0, 255));
    }
    
    private void cb_nominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_nominalActionPerformed
        if(cb_nominal.getSelectedIndex() == 0) {
            this.harga = lbl_rupiah.getText();
        }
    }//GEN-LAST:event_cb_nominalActionPerformed

    private void cb_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_pembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_pembayaranActionPerformed

    private void lbl_bayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_bayarMouseClicked
        this.saldo = Integer.parseInt(lbl_rupiah.getText().trim());
        String cek = EmptyValidation.cekTopupSaldo(cb_nominal,cb_pembayaran);

        if(cek.equals("valid")) {
            this.harga = cb_nominal.getSelectedItem().toString();
            this.saldo += Integer.parseInt(this.harga);
            lbl_rupiah.setText(String.valueOf(this.saldo));
            
            JOptionPane.showMessageDialog(null, "SELAMAT! TOPUP " + this.harga + " KAMU BERHASIL", "TOPUP BERHASIL", JOptionPane.INFORMATION_MESSAGE);
            
            set_data();
            String simpan = new Transaksi().tambah_data(username, id, kode_pembayaran, jenis_topup, hargadb, sisa_saldo);
        } else {
            JOptionPane.showMessageDialog(null, cek);
        }  
    }//GEN-LAST:event_lbl_bayarMouseClicked

    private void panel_gambarTopupMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_gambarTopupMouseDragged
       panel_gambarTopup.setCursor(Cursor.getPredefinedCursor(Cursor.MOVE_CURSOR));
       
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();

       this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panel_gambarTopupMouseDragged

    private void panel_gambarTopupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_gambarTopupMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panel_gambarTopupMousePressed

    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
        Menu Menu = new Menu(this.user);
        
        this.setVisible(false);
        Menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_backMouseClicked

    private void panel_gambarTopupMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_gambarTopupMouseReleased
    panel_gambarTopup.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_panel_gambarTopupMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_nominal;
    private javax.swing.JComboBox<String> cb_pembayaran;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_bayar;
    private javax.swing.JLabel lbl_gambar;
    static javax.swing.JLabel lbl_rupiah;
    private javax.swing.JLabel lempar_user;
    private javax.swing.JPanel panel_gambarTopup;
    // End of variables declaration//GEN-END:variables
}
